version: '3'
services:
  app:
    image: node:alpine    
    volumes:
      - ./:/opt/minienv
    working_dir: /opt/minienv
    environment:
      - NPM_PROXY_CACHE=${MINIENV_NPM_PROXY_CACHE}
    command: sh -c "npm --proxy ${NPM_PROXY_CACHE} --https-proxy ${NPM_PROXY_CACHE} --strict-ssl false install && npm --proxy ${NPM_PROXY_CACHE} --https-proxy ${NPM_PROXY_CACHE} --strict-ssl false install -g nodemon && nodemon --exec \"npm start\""
    ports:
     - "$port:$port"