version: '3'
services:
  minienv:
    image: minienv/minienv:latest
    privileged: true
    ports:
      - "30081:30081"
      - "30082:30082"
      - "30083:30083"
    environment:
      - MINIENV_LOG_PORT=30081
      - MINIENV_EDITOR_PORT=30082
      - MINIENV_PROXY_PORT=30083
      - MINIENV_GIT_REPO=${GIT_REPO}
