version: '3'
services:
  log:
    image: minienv/minienv-log:${MINIENV_VERSION}
    volumes:
      - ./:/dc
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MINIENV_DIR=/dc
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
      - MINIENV_NODE_HOST_PROTOCOL=${MINIENV_NODE_HOST_PROTOCOL}
    ports:
      - "${MINIENV_LOG_PORT}:8080"
  editor:
    image: minienv/minienv-editor:${MINIENV_VERSION}
    volumes:
      - ./:/dc
    environment:
      - MINIENV_DIR=/dc
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
    ports:
      - "${MINIENV_EDITOR_PORT}:80"
  proxy:
    image: minienv/minienv-proxy:${MINIENV_VERSION}
    environment:
      - MINIENV_TARGET_HOST=dind
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
    extra_hosts:
      - "dind:${DIND_IP_ADDRESS}"
    ports:
      - "${MINIENV_PROXY_PORT}:80"