version: '2'
services:
  log:
    image: minienv/minienv-log:latest
    volumes:
      - ./:/dc
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MINIENV_DIR=/dc
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
    ports:
      - "${MINIENV_LOG_PORT}:8080"
  editor:
    image: minienv/minienv-editor:latest
    volumes:
      - ./:/dc
    environment:
      - MINIENV_DIR=/dc
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
    ports:
      - "${MINIENV_EDITOR_PORT}:80"
  proxy:
    image: minienv/minienv-proxy:latest
    environment:
      - MINIENV_TARGET_HOST=dind
      - MINIENV_ALLOW_ORIGIN=${MINIENV_ALLOW_ORIGIN}
    extra_hosts:
      - "dind:${DIND_IP_ADDRESS}"
    ports:
      - "${MINIENV_PROXY_PORT}:80"