apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: minienv-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minienv-api
    spec:
      containers:
        - name: minienv-api
          image: localhost:5000/minienv/minienv-api-kube:0.2.0-DEV
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
          env:
          - name: MINIENV_VERSION
            value: "0.2.0-DEV"
          - name: MINIENV_NODE_NAME_OVERRIDE
            value: "192.168.99.100"
          - name: MINIENV_PROVISION_COUNT
            value: "1"
          - name: MINIENV_PROVISION_VOLUME_SIZE
            value: "10Gi"
          - name: MINIENV_PROVISION_IMAGES
            value: "node:alpine"
          - name: MINIENV_REPO_WHITELIST
            value: "Master Branch|https://github.com/minienv/minienv-example|master,Test Branch|https://github.com/minienv/minienv-example|test"
          - name: MINIENV_ALLOW_ORIGIN
            value: "http://minikube.loc"
          - name: KUBERNETES_TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: MINIENV_NODE_HOST_NAME
            value: "minikube.loc"
          - name: MINIENV_NODE_HOST_PROTOCOL
            value: "http"
          - name: MINIENV_NAMESPACE
            value: "minienv"
          - name: MINIENV_STORAGE_DRIVER
            value: "vfs"
          - name: MINIENV_REDIS_ADDRESS
            value: "minienv-redis-service:6379"
          - name: MINIENV_REDIS_DB
            value: "0"