apiVersion: v1
kind: Service
metadata:
  name: minienv-web-service
spec:
  selector:
    app: minienv-web
  ports:
    - protocol: TCP
      port: 80
      name: "web"
      nodePort: 31111
  type: NodePort
