apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: minienv-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minienv-api
    spec:
      containers:
        - name: minienv-api
          image: localhost:5000/minienv/minienv-api-kube:latest
          resources:
            limits:
              memory: "256Mi"
          env:
          - name: MINIENV_VERSION
            value: "latest"
          - name: MINIENV_NODE_NAME_OVERRIDE
            value: "192.168.99.100"
          - name: MINIENV_PROVISION_COUNT
            value: "1"
          - name: MINIENV_PROVISION_VOLUME_SIZE
            value: "10Gi"
          - name: MINIENV_PROVISION_IMAGES
            value: "rethinkdb:latest,node:alpine"
          - name: MINIENV_REPO_WHITELIST
            value: "https://github.com/markwatsonatx/tutorial-docker-compose-nodejs-intro,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-crud,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-rps"
          - name: MINIENV_ALLOW_ORIGIN
            value: "http://minikube.loc:31111"
          - name: KUBERNETES_TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: MINIENV_NODE_HOST_NAME
            value: "minikube.loc"
          - name: MINIENV_NAMESPACE
            value: "minienv"
          - name: MINIENV_STORAGE_DRIVER
            value: "vfs"