apiVersion: v1
kind: Service
metadata:
  name: minienv-api-service
spec:
  selector:
    app: minienv-api
  ports:
    - protocol: TCP
      port: 80
      name: "web"
      nodePort: 31112
  type: NodePort
