version: '3'
services:
  minienv-registry:
    image: minienv/minienv-registry:latest
    networks:
      - minienv-network
    deploy:
      mode: global
    ports:
      - "5000:5000"
  minienv-npm-proxy-cache:
    image: minienv/minienv-npm-proxy-cache:latest
    networks:
      - minienv-network
    deploy:
      mode: global
    ports:
      - "5001:5001"
  minienv-api:
    image: minienv/minienv-api-swarm:latest
    depends_on:
      - minienv-registry
    networks:
      - minienv-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    ports:
      - "31112:8080"
    environment:
      - MINIENV_PROVISION_COUNT=1
      - MINIENV_PROVISION_IMAGES=rethinkdb:latest,node:alpine,ibmcom/cloudant-developer:latest,markwatsonatx/spark-notebook:2.1.1
      - MINIENV_REPO_WHITELIST=https://github.com/markwatsonatx/tutorial-docker-compose-nodejs-intro,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-crud,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-rps,https://github.com/markwatsonatx/tutorial-spark-notebook-wordcount-scala
      - MINIENV_ALLOW_ORIGIN=http://localhost:31111
      - MINIENV_NODE_HOST_NAME=localhost
      - MINIENV_STORAGE_DRIVER=aufs
  minienv-web:
    image: minienv/minienv-web:latest
    depends_on:
      - minienv-registry
      - minienv-api
    networks:
      - minienv-network
    ports:
      - "31111:80"
    environment:
      - MINIENV_API_URL=http://localhost:31112
networks:
  minienv-network: