version: '3.2'
services:
  minienv-registry:
    image: minienv/minienv-registry:latest
    networks:
      - minienv-network
    deploy:
      mode: global
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
  minienv-npm-proxy-cache:
    image: minienv/minienv-npm-proxy-cache:latest
    networks:
      - minienv-network
    deploy:
      mode: global
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
        mode: host
  minienv-api:
    image: minienv/minienv-api-swarm:latest
    depends_on:
      - minienv-registry
    networks:
      - minienv-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "31112:8080"
    environment:
      - COMPOSE_HTTP_TIMEOUT=180
      - MINIENV_PROVISION_COUNT=2
      - MINIENV_PROVISION_VOLUME_DRIVER=rexray/ebs
      - MINIENV_PROVISION_VOLUME_DRIVER_OPTS=size:20
      - MINIENV_PROVISION_IMAGES=rethinkdb:latest,node:alpine,ibmcom/cloudant-developer:latest,markwatsonatx/spark-notebook:2.1.1
      - MINIENV_REPO_WHITELIST=https://github.com/markwatsonatx/tutorial-docker-compose-nodejs-intro,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-crud,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-rps,https://github.com/markwatsonatx/tutorial-spark-notebook-wordcount-scala
      - MINIENV_ALLOW_ORIGIN=http://aws.minienv.com:31111
      - MINIENV_NODE_HOST_NAME=aws.minienv.com
      - MINIENV_STORAGE_DRIVER=overlay2
  minienv-web:
    image: minienv/minienv-web:latest
    depends_on:
      - minienv-registry
      - minienv-api
    networks:
      - minienv-network
    ports:
      - "31111:80"
    environment:
      - MINIENV_API_URL=http://aws.minienv.com:31112
networks:
  minienv-network:
    driver: overlay
