apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: exampleup-web-deployment 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exampleup-web
    spec:
      containers:
        - name: exampleup-web
          image: localhost:5000/markwatsonatx/exampleup-web:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: EXUP_API_URL
            value: "http://minikube.dev:31112"
