apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: minienv-registry-daemonset
  name: minienv-registry-daemonset
spec:
  template:
    metadata:
      labels:
        app: minienv-registry
    spec:
      hostNetwork: true
      containers:
      - name: minienv-registry
        image: markwatsonatx/minienv-registry:latest
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
