apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: example-1-deployment 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-1
    spec:
      containers:
        - name: minienv
          image: localhost:5000/markwatsonatx/minienv:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          securityContext:
            privileged: true
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: EXUP_STORAGE_DRIVER
            value: "vfs"
          - name: EXUP_LOG_PORT
            value: "33001"
          - name: EXUP_EDITOR_PORT
            value: "33002"
          - name: EXUP_PROXY_PORT
            value: "33003"
          - name: EXUP_GIT_REPO
            value: "https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-changes" 
