apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: minienv-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minienv-api
    spec:
      containers:
        - name: minienv-api
          image: localhost:5000/minienv/minienv-api-kube:0.2.0-DEV
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
          env:
          - name: MINIENV_VERSION
            value: "0.2.0-DEV"
          - name: MINIENV_PROVISION_COUNT
            value: "4"
          - name: MINIENV_PROVISION_VOLUME_SIZE
            value: "20Gi"
          - name: MINIENV_PROVISION_IMAGES
            value: "rethinkdb:latest,node:alpine,ibmcom/cloudant-developer:latest,markwatsonatx/spark-notebook-ml:2.1.1,markwatsonatx/pixiedust-python27-spark163-alpine:1.1.7.1,markwatsonatx/tutorial-polymer-shop-hoodie:latest"
          - name: MINIENV_REPO_WHITELIST
            value: "https://github.com/markwatsonatx/tutorial-docker-compose-nodejs-intro,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-crud,https://github.com/markwatsonatx/tutorial-rethinkdb-nodejs-rps,https://github.com/markwatsonatx/tutorial-spark-notebook-wordcount-scala,https://github.com/markwatsonatx/tutorial-watson-ml-intro,https://github.com/markwatsonatx/tutorial-pixiedust,https://github.com/markwatsonatx/tutorial-polymer-shop-hoodie-cloudant"
          - name: MINIENV_ALLOW_ORIGIN
            value: "http://bx.minienv.com:31111"
          - name: KUBERNETES_TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: MINIENV_NODE_HOST_NAME
            value: "bx.minienv.com"
          - name: MINIENV_NAMESPACE
            value: "minienv"
          - name: MINIENV_STORAGE_DRIVER
            value: "aufs"