apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: minienv-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minienv-api
    spec:
      containers:
        - name: minienv-api
          image: localhost:5000/minienv/minienv-api-kube:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: MINIENV_ALLOW_ORIGIN
            value: "http://minikube.dev:31111"
          - name: KUBERNETES_TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: MINIENV_NODE_HOST_NAME
            value: "minikube.dev"
          - name: MINIENV_NAMESPACE
            value: "minienv"
          - name: MINIENV_STORAGE_DRIVER
            value: "aufs"
